//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShrackForStudents.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ShrackForStudents.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string res_register_emailLabel {
            get {
                return ResourceManager.GetString("res_register_emailLabel", resourceCulture);
            }
        }
        
        public static string res_register_emailPlaceholder {
            get {
                return ResourceManager.GetString("res_register_emailPlaceholder", resourceCulture);
            }
        }
        
        public static string res_register_firstNameLabel {
            get {
                return ResourceManager.GetString("res_register_firstNameLabel", resourceCulture);
            }
        }
        
        public static string res_register_gdprText {
            get {
                return ResourceManager.GetString("res_register_gdprText", resourceCulture);
            }
        }
        
        public static string res_register_headingLabel {
            get {
                return ResourceManager.GetString("res_register_headingLabel", resourceCulture);
            }
        }
        
        public static string res_register_lastNameLabel {
            get {
                return ResourceManager.GetString("res_register_lastNameLabel", resourceCulture);
            }
        }
        
        public static string res_register_nickNameLabel {
            get {
                return ResourceManager.GetString("res_register_nickNameLabel", resourceCulture);
            }
        }
        
        public static string res_register_passwordLabel {
            get {
                return ResourceManager.GetString("res_register_passwordLabel", resourceCulture);
            }
        }
        
        public static string res_register_privacyText {
            get {
                return ResourceManager.GetString("res_register_privacyText", resourceCulture);
            }
        }
        
        public static string res_register_reEnterPwdLabel {
            get {
                return ResourceManager.GetString("res_register_reEnterPwdLabel", resourceCulture);
            }
        }
        
        public static string res_register_registerBtn {
            get {
                return ResourceManager.GetString("res_register_registerBtn", resourceCulture);
            }
        }
        
        public static string res_register_schoolNameLabel {
            get {
                return ResourceManager.GetString("res_register_schoolNameLabel", resourceCulture);
            }
        }
        
        public static string res_register_tAndCText {
            get {
                return ResourceManager.GetString("res_register_tAndCText", resourceCulture);
            }
        }
        
        public static string res_error_error {
            get {
                return ResourceManager.GetString("res_error_error", resourceCulture);
            }
        }
        
        public static string res_error_authenticationFailed {
            get {
                return ResourceManager.GetString("res_error_authenticationFailed", resourceCulture);
            }
        }
        
        public static string res_error_noDetailsFound {
            get {
                return ResourceManager.GetString("res_error_noDetailsFound", resourceCulture);
            }
        }
        
        public static string res_message_oK {
            get {
                return ResourceManager.GetString("res_message_oK", resourceCulture);
            }
        }
    }
}
